### ISSUE TITLE
Tiki installer goes back to initial screen after "select language" screen

### ISSUE THREAD

**Issue by sandroandrade** [fabiomontefuscolo/docker-tikiwiki#3]
Hi,

I managed to have a mariadb and tiki docker images running fine. When running the installer, it logins successfully with provided database username and password but it returns to initial installer screen after selecting the language and clicking in "Continue".

Any hint?

**Comment by fabiomontefuscolo** [comment]
Hi Sandro,

I confirm this for Tiki **17**, but not for **18.4** and **19**. Can you try the updated images?

**Comment by fabiomontefuscolo** [comment]
Looking to the 17.x history, I think they are not supporting this version anymore.
